title: AI & Civilization
description: Exploring the intersection of Artificial Intelligence, Optimization, and Human Progress
remote_theme: daattali/beautiful-jekyll@master
author: Yanis
future: true
