title: AI & Civilization
description: Exploring the intersection of Artificial Intelligence, Optimization, and Human Progress
remote_theme: daattali/beautiful-jekyll@master
author: Yanis Labeyrie
author_desc: "Optimization & Artificial Intelligence Enthusiast. I build systems to automate the tedious and optimize the complex."
navbar-title: "AI & Civilization"
future: true
url: "https://aiandcivilization.github.io"
baseurl: "/ai_and_civilization"

# Enable MathJax site-wide
mathjax: true
